databases:
  - name: stellar
    databaseName: stellar
    user: stellar

services:
  - type: web
    name: KTechNets
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn KTechNets.wsgi:Stellar"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Stellar
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4