# Generated by Django 2.0.1 on 2018-02-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='query',
        ),
    ]
