# Generated by Django 2.0.1 on 2018-03-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0002_auto_20180228_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
    ]
