# Generated by Django 2.0.1 on 2018-03-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0003_remove_answer_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='query',
            name='query_title',
            field=models.CharField(default='Latest Fed Statement', max_length=1200),
        ),
    ]
