# Generated by Django 2.0.1 on 2018-03-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0004_auto_20180302_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_title',
            field=models.CharField(default='Or find out what Hawkwartchers thinks about the latest Fed Statement!', max_length=1200),
        ),
    ]
