# Generated by Django 2.0.1 on 2018-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0007_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='answer',
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_text',
            field=models.CharField(max_length=3200),
        ),
    ]
