# Generated by Django 2.0.1 on 2018-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0008_auto_20180303_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_text',
            field=models.CharField(default='Find out what Hawkwatchers thinks about this Statement', max_length=1200),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_title',
            field=models.CharField(max_length=1200),
        ),
    ]
