# Generated by Django 2.0.1 on 2018-03-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0009_auto_20180303_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query_title',
        ),
        migrations.AlterField(
            model_name='query',
            name='query_text',
            field=models.CharField(default='Add your statemente here', max_length=1200),
        ),
    ]
