# Generated by Django 2.0.1 on 2018-03-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0011_auto_20180303_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='query',
            new_name='query_answer',
        ),
    ]
