# Generated by Django 2.0.1 on 2018-03-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0013_auto_20180304_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('query_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hawk_tracker.Query')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='query_method',
            field=models.CharField(default='NN', max_length=1200),
        ),
    ]
