# Generated by Django 2.0.1 on 2018-03-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0014_auto_20180304_1937'),
    ]

    operations = [

        migrations.DeleteModel(
            name='Predictor',
        ),
    ]
