# Generated by Django 2.0.1 on 2018-03-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0015_auto_20180304_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_answer',
            field=models.CharField(default='NEUTRAL', max_length=1200),
        ),
    ]
