# Generated by Django 2.0.1 on 2018-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_tracker', '0017_auto_20180304_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_num',
            field=models.CharField(max_length=20),
        ),
    ]
