# Generated by Django 4.2.1 on 2023-05-29 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Stellar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artchoice_name", models.CharField(max_length=1200)),
                (
                    "artchoice_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("artchoice_method", models.CharField(default="NN", max_length=1200)),
                (
                    "artchoice_answer",
                    models.CharField(default="NEUTRAL", max_length=1200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtPath",
            fields=[
                (
                    "query_answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Stellar.artchoice",
                    ),
                ),
                ("artpath_text", models.CharField(max_length=200)),
                ("artpath_num", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Query",
        ),
    ]
