# Generated by Django 4.2.1 on 2023-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stellar", "0002_artchoice_artpath_delete_answer_delete_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="artchoice",
            name="artchoice_size",
            field=models.IntegerField(default=10),
        ),
    ]
