# Generated by Django 4.2.1 on 2023-05-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Stellar", "0003_artchoice_artchoice_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artchoice",
            name="artchoice_date",
        ),
    ]
